version: '3.8'

services:
  app:
    container_name: CategoryBotContainer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telegram_bot_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0702
      TG_BOT_NAME: CategoryBotPattern
      TG_BOT_TOKEN: 7736601299:AAGRoiJojGkL2_PG4YGWSETReNDGJBNS1bg
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0702
      POSTGRES_DB: telegram_bot_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: